apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pheasant.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "pheasant.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  pheasant.yaml: |
{{ .Values.config.pheasantYaml | indent 4 }}
