{{- if .Values.persistence.state.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncsage.fullname" . }}-state
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
{{- end }}
---
{{- if .Values.persistence.vault.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncsage.fullname" . }}-vault
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.vault.size }}
{{- end }}
