"""First-run bootstrap for ``syncsage up`` (Product Framework Step 30.1).

One command takes a directory from nothing to an indexed, queryable
knowledge base: detect what the directory is, generate a laptop-shaped
config if none exists, then hand off to the ordinary sync engine and
server. Everything here is config plumbing — indexing and serving reuse
the exact code paths behind ``syncsage sync`` and ``syncsage start``.

Generated configs anchor all state under ``.syncsage/{state,vault,exports}``
next to the config file (absolute paths, so later invocations from another
working directory keep hitting the same state). An existing config file is
never rewritten — re-running ``up`` reuses it unchanged.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

from syncsage.config.loader import deep_merge
from syncsage.config.profiles import profile_data
from syncsage.config.schema import SourceType, SyncSageConfig

STATE_DIRNAME = ".syncsage"


def _scrub(obj: Any) -> Any:
    """Drop ``None`` values and empty containers from a config dict.

    ``model_validate`` refills every dropped key with its default, and the
    dependency-light ``yaml`` shim used in offline test environments cannot
    round-trip ``None`` (it reloads as the string ``"None"``) or empty
    blocks — so the generated file simply omits them.
    """
    if isinstance(obj, dict):
        cleaned = {k: _scrub(v) for k, v in obj.items() if v is not None}
        return {k: v for k, v in cleaned.items() if v not in ({}, [])}
    if isinstance(obj, list):
        return [_scrub(v) for v in obj if v is not None]
    return obj


def _render_sources_block(entries: list[dict[str, str]]) -> str:
    """Render ``sources:`` by hand in the inline-first-key list style.

    The yaml shim's ``safe_dump`` writes list-of-dict items as a bare ``-``
    line it cannot itself re-read; both it and PyYAML parse this shape.
    """
    lines = ["sources:"]
    for entry in entries:
        prefix = "  - "
        for key, value in entry.items():
            lines.append(f"{prefix}{key}: {value}")
            prefix = "    "
    return "\n".join(lines) + "\n"


def detect_source_type(path: Path) -> SourceType:
    """Classify a local directory for the generated source entry."""
    if (path / ".obsidian").is_dir():
        return SourceType.obsidian_vault
    if (path / ".git").is_dir():
        return SourceType.repository
    return SourceType.document_folder


def slugify(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "workspace"


def render_up_config(
    target: Path,
    config_path: Path,
    *,
    name: str | None = None,
    port: int = 8765,
    profile: str = "quickstart",
) -> str:
    """Render the YAML for a single-source laptop config over ``target``.

    Deterministic for a given (target, config_path, options) tuple so a
    regenerated config is byte-identical — the idempotency bar every
    bootstrap command in this codebase has to clear.
    """
    target = target.resolve()
    local = (config_path.resolve().parent / STATE_DIRNAME).resolve()
    kb_name = name or slugify(target.name)
    source_type = detect_source_type(target)

    data: dict[str, Any] = deep_merge(
        SyncSageConfig().model_dump(mode="json"), profile_data(profile)
    )
    data["syncsage"].update(
        {
            "name": kb_name,
            "description": f"Personal knowledge base over {target}",
            "state_path": str(local / "state"),
            "vault_path": str(local / "vault"),
            "exports_path": str(local / "exports"),
            "workspace_root": str(target),
        }
    )
    data["server"]["port"] = port
    data["security"]["allow_workspace_roots"] = [
        str(target),
        str(local / "vault"),
        str(local / "exports"),
    ]
    data.pop("sources", None)
    sources_block = _render_sources_block(
        [
            {
                "name": kb_name,
                "type": source_type.value,
                "path": str(target),
                "description": f"Auto-detected {source_type.value}",
            }
        ]
    )
    header = (
        f"# Generated by `syncsage up` for {target}\n"
        f"# Source type auto-detected: {source_type.value}\n"
        "# Edit freely — `syncsage up` never overwrites an existing config.\n"
    )
    return header + yaml.safe_dump(_scrub(data), sort_keys=False) + sources_block


def ensure_up_config(
    target: Path,
    config_path: Path,
    *,
    name: str | None = None,
    port: int = 8765,
    profile: str = "quickstart",
) -> bool:
    """Write the generated config unless one already exists.

    Returns True when a new config was written, False when an existing
    file was left untouched (the reuse path).
    """
    if config_path.exists():
        return False
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        render_up_config(target, config_path, name=name, port=port, profile=profile),
        encoding="utf-8",
    )
    return True
