"""``syncsage host`` — one line from a folder to a running container.

``syncsage host ~/notes https://github.com/me/proj`` resolves the targets
exactly like ``syncsage up`` does, generates the same config, then writes
a compose file that mounts every local target read-only at a stable
in-container path and brings the stack up.

The generated compose file is a normal artifact: it is written to disk,
printed on request, and safe to commit. ``--print-only`` stops before
invoking Docker, which is also what the test suite uses — generating the
file must never require a Docker daemon.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from syncsage.mcp_client.vscode import DEFAULT_IMAGE_REPOSITORY
from syncsage.version import __version__

# Pinned to the SyncSage version rather than `latest`: the UI image is
# published from the same commit under the same tag, and a moving `latest` is
# the classic way to end up staring at a cached, months-old bundle after an
# upgrade (Docker will not re-pull a tag it already has locally).
DEFAULT_UI_IMAGE_REPOSITORY = "ghcr.io/esatt10/syncsage-ui"
DEFAULT_UI_IMAGE = f"{DEFAULT_UI_IMAGE_REPOSITORY}:{__version__}"
CONTAINER_SOURCE_ROOT = "/sources"


def _container_path(index: int, name: str) -> str:
    return f"{CONTAINER_SOURCE_ROOT}/{name or f'source-{index}'}"


def local_ui_context() -> str | None:
    """Path to this checkout's ``ui/`` directory, when running from source.

    A source checkout can be ahead of (or diverge from) the published UI
    image, so the generated compose file gets a ``build:`` stanza pointing at
    it. Compose builds that context when the pinned image is not already
    present locally, which also means a checkout works before the image for
    this version has been published at all. Installed-from-PyPI users have no
    ``ui/`` directory and simply pull the image.
    """
    candidate = Path(__file__).resolve().parents[3] / "ui"
    return str(candidate) if (candidate / "Dockerfile").is_file() else None


def render_compose(
    targets: list,
    *,
    config_path: Path,
    state_dir: Path,
    port: int,
    ui_port: int,
    image: str | None = None,
    ui_image: str | None = None,
    include_ui: bool = True,
    ui_build_context: str | None = None,
) -> str:
    """Compose YAML for the resolved targets. Deterministic for its inputs."""
    volumes = [
        f"{config_path}:/config/syncsage.yaml:ro",
        f"{state_dir / 'state'}:/state",
        f"{state_dir / 'vault'}:/vault",
        f"{state_dir / 'exports'}:/exports",
    ]
    for index, target in enumerate(targets):
        if not target.local:
            continue
        volumes.append(f"{target.path}:{_container_path(index, target.name)}:ro")

    syncsage: dict[str, Any] = {
        "image": image or f"{DEFAULT_IMAGE_REPOSITORY}:{__version__}",
        "container_name": "syncsage",
        "restart": "unless-stopped",
        "ports": [f"{port}:8765"],
        "environment": {"SYNCSAGE_CONFIG": "/config/syncsage.yaml"},
        "volumes": volumes,
        "healthcheck": {
            "test": ["CMD-SHELL", "curl -fsS http://127.0.0.1:8765/health || exit 1"],
            "interval": "30s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "20s",
        },
    }
    services: dict[str, Any] = {"syncsage": syncsage}
    if include_ui:
        ui: dict[str, Any] = {
            "image": ui_image or DEFAULT_UI_IMAGE,
            "container_name": "syncsage-ui",
            "restart": "unless-stopped",
            "ports": [f"{ui_port}:80"],
            "depends_on": {"syncsage": {"condition": "service_healthy"}},
        }
        # An explicit --ui-image is a deliberate choice of a published bundle;
        # only fall back to building when we are defaulting.
        if ui_build_context and not ui_image:
            ui["build"] = {"context": ui_build_context}
        services["syncsage-ui"] = ui
    header = (
        "# Generated by `syncsage host`. Safe to edit or commit.\n"
        "# Local sources are mounted read-only; state/vault/exports are bind\n"
        "# mounts so indexed data survives `docker compose down`.\n"
        "# Re-run with `up -d --build` after changing the UI source or config;\n"
        "# Compose reuses an existing local image otherwise.\n"
    )
    return header + yaml.safe_dump({"services": services}, sort_keys=False)


def host_stack(args) -> int:
    """Resolve targets, generate config + compose, and (unless asked not to) run it."""
    from syncsage.quickstart import ensure_up_config, state_root
    from syncsage.targets import fetch_target, resolve_targets

    config_path = Path(args.config).resolve()
    specs = args.path if isinstance(args.path, list) else [args.path]
    if not specs:
        specs = ["."]
    local_state = state_root(config_path)

    targets = resolve_targets(
        specs,
        clone_root=local_state / "sources",
        workspace=local_state / "external",
        split=args.split,
        name=args.name,
    )
    for target in targets:
        status = fetch_target(target)
        if status:
            print(status)

    created = ensure_up_config(
        targets, config_path, name=args.name, port=args.port, profile=args.profile
    )
    print(f"{'Wrote' if created else 'Reusing existing'} {config_path}")

    # The container sees each source under /sources/<name>, so rewrite the
    # config's paths for the containerized copy rather than leaking host
    # paths that do not exist inside the image.
    container_config = config_path.parent / f"{config_path.stem}.container{config_path.suffix}"
    _write_container_config(config_path, container_config, targets)

    for directory in ("state", "vault", "exports"):
        (local_state / directory).mkdir(parents=True, exist_ok=True)

    ui_context = None if args.no_ui or args.ui_image else local_ui_context()
    compose_path = Path(args.output).resolve()
    compose_path.write_text(
        render_compose(
            targets,
            config_path=container_config,
            state_dir=local_state,
            port=args.port,
            ui_port=args.ui_port,
            image=args.image,
            ui_image=args.ui_image,
            include_ui=not args.no_ui,
            ui_build_context=ui_context,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {compose_path}")

    # Built-from-source UI: rebuild on every run so the served bundle matches
    # the checkout. Compose would otherwise reuse whatever image already
    # carries this tag, which is how UI edits appear to have no effect.
    up_command = ["compose", "-f", str(compose_path), "up", "-d"]
    if ui_context:
        up_command.append("--build")

    if args.print_only:
        print(f"Start it with: docker {' '.join(up_command)}")
        return 0

    docker = shutil.which("docker")
    if docker is None:
        print(
            "ERROR: docker not found on PATH. The compose file is written; run it "
            f"with:\n  docker {' '.join(up_command)}",
            file=sys.stderr,
        )
        return 1
    result = subprocess.run([docker, *up_command], check=False)
    if result.returncode != 0:
        return result.returncode
    print(f"SyncSage API + MCP: http://localhost:{args.port}")
    if not args.no_ui:
        print(f"SyncSage UI:        http://localhost:{args.ui_port}")
        print(
            "  (the UI is empty until the first sync finishes — "
            f"check http://localhost:{args.port}/overview)"
        )
    return 0


def _write_container_config(source: Path, destination: Path, targets: list) -> None:
    """Copy the generated config with host paths remapped to /sources/<name>."""
    from syncsage.quickstart import _render_sources_block

    data = yaml.safe_load(source.read_text(encoding="utf-8")) or {}
    remapped = {}
    for index, target in enumerate(targets):
        if target.local:
            remapped[target.path] = _container_path(index, target.name)

    sources = data.pop("sources", []) or []
    for entry in sources:
        path = str(entry.get("path", ""))
        if path in remapped:
            entry["path"] = remapped[path]

    syncsage = data.setdefault("syncsage", {})
    syncsage.update(
        {
            "state_path": "/state",
            "vault_path": "/vault",
            "exports_path": "/exports",
            "workspace_root": CONTAINER_SOURCE_ROOT,
        }
    )
    security = data.setdefault("security", {})
    security["allow_workspace_roots"] = [
        CONTAINER_SOURCE_ROOT,
        "/vault",
        "/exports",
        *sorted(remapped.values()),
    ]
    destination.write_text(
        "# Generated by `syncsage host` — the in-container view of your config.\n"
        # `sources` is rendered by hand for the same reason `syncsage up`
        # does it: safe_dump writes list-of-dict items in a shape the
        # dependency-light yaml shim cannot read back.
        + yaml.safe_dump(data, sort_keys=False)
        + _render_sources_block(sources),
        encoding="utf-8",
    )
    print(f"Wrote {destination}")
