apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pheasant-state
  namespace: pheasant
  labels:
    app.kubernetes.io/name: pheasant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
