apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncsage-state
  namespace: syncsage
  labels:
    app.kubernetes.io/name: syncsage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncsage-vault
  namespace: syncsage
  labels:
    app.kubernetes.io/name: syncsage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
